# Site
name: "The Library Backup"
title: "The Library Backup"
description: >-
  Backup of casts by the community in "the-library" warpcast channel
logo: "assets/library.png"
# favicon: 'assets/images/logo.png'
baseurl: ""
url: ""
# include: ["_pages"]
permalink: /:slug.html

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-figure

# Pagination

paginate: 20
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, "warpcast.rb", "README.md", ".gitignore", "_json"]
