# Site
name: "The Library Backup"
title: "The Library Backup"
description: >-
  Backup of casts published by the community in "the-library" warpcast channel
logo: "assets/library.png"
# favicon: 'assets/images/logo.png'
baseurl: "/the-library"
url: "https://nftbiker.github.io"
# include: ["_pages"]
permalink: :slug.html

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-figure

# Pagination

paginate: 20
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

feed:
  posts_limit: 25

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

collections:
  authors:
    output: true
    permalink: /user/:title

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, "warpcast.rb", "README.md", ".gitignore", "_json"]
