name: Update library archive

on:
  schedule:
    - cron: "12 6,12,18,24 * * *" # Runs every 6 hours
  workflow_dispatch:

jobs:
  update-restricted:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run script
        run: |
          ruby ./warpcast.rb

      - name: Commit and Push Changes if any
        run: |
          if ! git diff --exit-code; then
            git config --global user.name "GitHub Bot"
            git config --global user.email "actions@github.com"

            timestamp=$(date +'%Y%m%d%H%M%S')
            branch_name="update-file-$timestamp"

            git checkout -b "$branch_name"
            git add -A
            git commit -m "Update archive"
            git push origin "$branch_name"

            git checkout main
            git merge --no-ff "$branch_name"
            git push origin main

            # delete the temporary branch
            git branch -d "$branch_name"
            git push origin --delete "$branch_name"
          fi
